### ISSUE TITLE
Create script not run when database is empty

### ISSUE THREAD

**Issue by mikaelrjohansson** [mattiasnordqvist/Galactic-Waste-Management#15]
The create script is not run when the database is empty and throws and sql exception saying that SchemaVersionJournal does not exist. If the SchemaVersionJournal-table is not created, it should be. One does not want to hack around that.

**Comment by mattiasnordqvist** [comment]
Nice! I'll fix it tonight. Thank you!

**Comment by mattiasnordqvist** [comment]
In the meantime... remove the database in its entirety. It will be created by gwm

**Comment by mattiasnordqvist** [comment]
As long as you have access to the master database, that is
