### ISSUE TITLE
Allow transactions per script

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiasnordqvist/Galactic-Waste-Management#2]
Currently, GWM is using a single fat ass transaction for the whole migrations. Could we give the user the option to split the migration in multiple transactions?

**Comment by carl-berg** [comment]
I like 1 transaction/script

**Comment by mattiasnordqvist** [comment]
Actually, I don't think I see the point... at least not in a production environment. You don't want half a release to go live. I'll make it configurable if it's an easy fix. Otherwise I'll just make sure transactions are started at the right place, which I'm not sure they're doing now.

**Comment by carl-berg** [comment]
+1 for configurable with one transaction wrapping all migrations as default

**Comment by mattiasnordqvist** [comment]
Can now be configured with parameter transaction-per-script, which defaults to false
