### ISSUE TITLE
Managing rc versions in LiveField

### ISSUE THREAD

**Issue by carl-berg** [mattiasnordqvist/Galactic-Waste-Management#31]
I'm having some issues deploying migration to _LiveField_ when incrementing by release-candidates. Maybe i'm just not supposed to be doing that?
First time i deployed something i moved migrations into _Migrations/1.0.0_ and the deployed successfully to a test environment. Application version was at this stage _1.0.0-rc.1_ I also switched over my local configuration to _BrownField_. So far so good.

But when i wanted to add more migrations i ran into problems. First i tried moving the new scripts into the existing _1.0.0_ folder but got an error, then switched the structure around to _1.0.0-rc.1_ for the first ones _1.0.0-rc.3_ for the next and so on, then wiped the database and started over which worked fine but still get errors  next time i added a new rc-folder. 

What's the perscribed way to do this? In the `SchemaVersionJournal` all migrations get Version _1.0_. Do i need to make minor or patch -increments to the version to get GWM to pick up on version changes? It was a bit unclear to me from the docs that i couldn't add scripts to an existing folder (but may be a good practice). I understood that the existing scripts were cemented but not that the version-folder also was cemented.

**Comment by carl-berg** [comment]
I'll see if i can hack together a custom Versioning Setting that replaces the default one that works for this case.

**Comment by carl-berg** [comment]
I hacked togeather a custom migration versioning that supports semver 2 which is the style of versioning i've been using in this project and it seems to work. Good job making the library extendable @mattiasnordqvist 🎉!

**Comment by mattiasnordqvist** [comment]
If I remember correctly, you can't add script to the same SchemaVersion (1.0) if that version is already "deployed". GWM thinks that new scripts in an already released version are not supposed to exist. Thats why you get an error message. GWMs default behaviour translates 1.0.0-rc1 and 1.0.0-rc2 to the same schema version (1.0). (which I think is correct when 1.0.0 ultimately is released.)

My thinking is that you should not have switched to brownfield until 1.0 was actually released. Upcoming release candidates of 1.0 (in my not so strong opinion) SHOULD be able to make changes to existing 1.0-scripts.

However, I'm willing to discuss this in September. :) Glad you found your way to making your own Migrations Versioning strategy. Maybe you should release it as a seperate package? :)
