### ISSUE TITLE
Schema when creating SchemaVersionJournal

### ISSUE THREAD

**Issue by hampustoren** [mattiasnordqvist/Galactic-Waste-Management#34]
I got the following error in the output console: 
#### GALACTIC WASTE MANAGER ENGAGED ####
Managing galactic waste in ****
Running LiveField mode
Using parameter: skip-create=False
Creating table for schema versioning.
Executing script 'CreateSchemaVersionJournal'
Value cannot be null.
Parameter name: input

When I looked in the database I saw that the schema for SchemaVersionJournal was my database user id instead of the expected dbo, i.e. [*userid*].[SchemaVersionJournal] and not [dbo].[SchemaVersionJournal].

After manually creating [dbo].[SchemaVersionJournal] in the database there was no issue any longer.

**Comment by mattiasnordqvist** [comment]
I'd say there are three ways you could fix this:
1. Like you did.
2. Have a look at the CreateSchemaVersionJournal class, copy it and create a fixed version of it:
```csharp
public class MyCreateSchemaVersionJournal : ScriptBase
        {
            public override string Name => nameof(CreateSchemaVersionJournal);

            public override IScriptType Type => ScriptType.Initialize;

            public override string Sql => @"
IF OBJECT_ID(N'dbo.SchemaVersionJournal', N'U') IS NULL BEGIN

CREATE TABLE dbo.SchemaVersionJournal (
    [Id] int identity(1,1) not null constraint PK_SchemaVersionJournal_Id primary key,
    [Version] nvarchar(255) not null,                    
    [Name] nvarchar(255) not null,
    [Applied] datetime2 not null,
    [Hash] nvarchar(255) not null,
	[Type] nvarchar(255) not null,
);
END";
        }
```

Then subclass BuiltInScriptsScriptProvider and replace CreateSchemaVersionJournal with your newly created MyCreateSchemaVersionJournal. (However, override of method is not possible, gonna virtualize it to the next version)

```csharp
public class MySpecializedScriptProvider : BuiltInScriptsScriptProvider
        {
            public override IEnumerable<IScript> GetScripts(IScriptType scriptType)
            {
                if (scriptType == ScriptType.Initialize)
                {
                    yield return new MyCreateSchemaVersionJournal();
                }
                if (scriptType == ScriptType.Drop)
                {
                    yield return new DropSchema();
                }
            }
        }
```
Then create your own ProjectSettings
```csharp
public class MyProjectSettings : ProjectSettings
        {
            public MyProjectSettings() : base(
                new DefaultMigrationVersioning(),
                new List<IScriptProvider>
                {
                    new MySpecializedScriptProvider(),
                    new EmbeddedScriptProvider(Assembly.GetAssembly(typeof(Program)), "Scripts")
                })
            { }
        }
```
And then use it when create the wastemanager:

```csharp
var wasteManager = GalacticWasteManager.Create(new MyProjectSettings(),migrationConfig["ConnectionString"]); 
```

3. Download next version 0.21.0, coming in a few minutes.

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @hampustoren for bug

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @hampustoren for bug
