### ISSUE TITLE
Test-Mode?

### ISSUE THREAD

**Issue by carl-berg** [mattiasnordqvist/Galactic-Waste-Management#36]
I'm starting to use GWM in integration tests and wasn't quite sure which mode to use?
- GreenField won't like it if there exists versioned scripts 
- BrownField doesn't like it if the database exists, but is empty (expects SchemaVersionJournal table to exist)
- LiveField doesn't use vNext (if memory serves me right)?

To get around this i've created a custom mode
```csharp
    public class TestFieldMigration : BrownFieldMigration
    {
        public TestFieldMigration() => Name = "TestField";

        /// <summary>
        /// Ensure that SchemaVersionJournal is created
        /// </summary>
        public override async Task ManageWaste()
        {
            var hasSchemaVersionJournal = await SchemaVersionJournalExists();
            if (!hasSchemaVersionJournal)
            {
                Logger.Log("Creating table for schema versioning.", "info");
                await Initialize();
            }

            await base.ManageWaste();
        }
    }
```
Is this the right way, or is there something else i should be using here @mattiasnordqvist?

**Comment by mattiasnordqvist** [comment]
I'd say this is the way... I'm not sure how this will interact with the base class, but it looks fine.

**Comment by mattiasnordqvist** [comment]
Should the test-mode be built-in? @carl-berg

**Comment by carl-berg** [comment]
I don't know... I guess it depends on what state your database is in before migration. In my case, for integration testing, the database exists but is completely empty. I can't remember but I think BrownField might work if the db doesn't exist...?
