### ISSUE TITLE
Target netstandard2.0

### ISSUE THREAD

**Issue by carl-berg** [mattiasnordqvist/Galactic-Waste-Management#37]
Is there a reason GWM targets `netcoreapp2.2` instead of `netstandard2.0`? As far as i can see _SuperNotUnderstandableInputHandling_ and _ArtisticPastelPainter_ also targets `netcoreapp2.2` but seem like they could target `netstandard2.0` instead which would also enable GWM to use `netstandard2.0`?

The issue for me is that i have a project that targets net472 that can't reference GWM...

**Comment by carl-berg** [comment]
Also... is there a reason `Microsoft.Extensions.Configuration.Abstractions` is referenced from file and not the [nuget](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Abstractions/2.2.0)?

**Comment by mattiasnordqvist** [comment]
looks like we have to get https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/150.4316.1-preview out of the deps to make it netstandard compliant

**Comment by mattiasnordqvist** [comment]
SuperNotUnderstandableInputHandling and ArtisticPastelPainter are both fixed now though (not released yet)

**Comment by carl-berg** [comment]
I think you can just upgrade dacfx to latest preview

**Comment by mattiasnordqvist** [comment]
Oh of course. I didnt find any because my include preview box wasnt checked. Thanks. I was just about to release a multitargeted version...

**Comment by mattiasnordqvist** [comment]
v0.22 uploaded to nuget.

**Comment by mattiasnordqvist** [comment]
@all-contributors please add @carl-berg for ideas
